Source/src/Orchard.Web/Modules/Orchard.MediaPicker/ViewModels/MediaGalleryFieldViewModel.cs
using System.Collections.Generic;
using Orchard.MediaPicker.Fields;

namespace Orchard.MediaPicker.ViewModels {

    public class MediaGalleryFieldViewModel {

        public ICollection<MediaGalleryItem> Items { get; set; }
        public string SelectedItems { get; set; }
        public MediaGalleryField Field { get; set; }
    }
}

Source/src/Orchard.Web/Modules/Orchard.MediaPicker/Controllers/AdminController.cs
using System;
using System.Web;
using System.Web.Mvc;
using Orchard.Localization;
using Orchard.Media;
using Orchard.Media.Services;
using Orchard.Media.ViewModels;
using Orchard.Themes;

namespace Orchard.MediaPicker.Controllers {
    [Themed(false)]
    public class AdminController : Controller {
        private readonly IMediaService _mediaService;

        public IOrchardServices Services { get; set; }

        public AdminController(IOrchardServices services, IMediaService mediaService) {
            Services = services;
            _mediaService = mediaService;

            T = NullLocalizer.Instance;
        }

        public Localizer T { get; set; }

        public ActionResult Index(string name, string mediaPath) {
            var mediaFolders = _mediaService.GetMediaFolders(mediaPath);
            var mediaFiles = string.IsNullOrEmpty(mediaPath) ? null : _mediaService.GetMediaFiles(mediaPath);
            var model = new MediaFolderEditViewModel { FolderName = name, MediaFiles = mediaFiles, MediaFolders = mediaFolders, MediaPath = mediaPath };
            ViewData["Service"] = _mediaService;
            return View(model);
        }

        [HttpPost]
        public JsonResult CreateFolder(string path, string folderName) {
            if (!Services.Authorizer.Authorize(Permissions.ManageMedia)) {
                return Json(new { Success = false, Message = T("Couldn't create media folder").ToString() });
            }

            try {
                _mediaService.CreateFolder(HttpUtility.UrlDecode(path), folderName);
                return Json(new { Success = true, Message = "" });
            }
            catch (Exception exception) {
                return Json(new { Success = false, Message = T("Creating Folder failed: {0}", exception.Message).ToString()} );
            }
        }
    }
}

Source/src/Orchard.Web/Modules/Orchard.MediaPicker/Views/Admin/Index.cshtml
@using Orchard.Media.Extensions;
@using Orchard.Media.Helpers;
@using Orchard.Media.Services;
@using Orchard.Media.Models;
@using Orchard.UI.Resources;
@{
    // these need to be in the head because MediaBrowser.js defines a callback that the thumbnail images call when they load,
    // which could happen as soon as they render.
    Style.Require("jQueryUI_Orchard").AtHead();
    Script.Require("jQueryUI_Tabs").AtHead();
    Script.Include("MediaBrowser.js").AtHead();

    SetMeta("IE=edge,chrome=1", httpEquiv: "X-UA-Compatible");
    Style.Include("~/themes/theadmin/styles/site.css");
    Style.Include("~/themes/theadmin/styles/ie.css").UseCondition("lte IE 8").SetAttribute("media", "screen, projection");
    Style.Include("~/themes/theadmin/styles/ie6.css").UseCondition("lte IE 6").SetAttribute("media", "screen, projection");
    Style.Include("mediapicker.css");

}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>@T("Pick Image")</title>
    @Display.Metas()
    @Display.HeadScripts()
    @Display.HeadLinks()
    @Display.StyleSheetLinks()
</head>
<body id="orchardmediapicker">

<script type="text/javascript">
 $.mediaPicker.cannotPerformMsg="@T("Cannot perform requested operation")";
 $.mediaPicker.accessDeniedMsg="@T("Authentication timed-out: please log-on again")";
 $.mediaPicker.logonUrl="@Url.Action("LogOn", new { Controller = "Account", Area = "Orchard.Users" })";
</script>

<div id="tabs" class="group">
    <ul>
        <li><a href="#tab-url" data-edittext="@T("Update/Upload Image")" data-edittext-content="true">@T("Insert/Upload Image")</a></li>
        <li><a href="#tab-gallery">@T("Browse Media")</a></li>
    </ul>
    <div id="tab-url">
@Html.Partial("Tab_Url", (object)Model)
    </div>
    <div id="tab-gallery">
@Html.Partial("Tab_Gallery", (object)Model)
    </div>
</div>


@Display.FootScripts()
</body>
</html>

Source/src/Orchard.Web/Modules/Orchard.MediaPicker/Views/Admin/Tab_Gallery.cshtml
@model Orchard.Media.ViewModels.MediaFolderEditViewModel
@using Orchard.Media.Extensions;
@using Orchard.Media.Helpers;
@using Orchard.Media.Services;
@using Orchard.Media.Models;
@using Orchard.UI.Resources;
@helper FolderLink(string folderName, string mediaPath) {
	// querystring values need to persist after a new GET when clicking on the media browser's
	// folders for navigation.
    @Html.ActionLink(folderName, "Index", null, null, null, "tab=1", new {
        callback = Request["callback"],
		uploadpath = Request["uploadpath"],
		editmode = Request["editmode"],
		name = folderName,
		mediaPath = mediaPath }, null);
}
@{
    var uploadAction = Url.Action("AddFromClient", "Admin", new { area = "Orchard.Media" });
}
        <div id="gallery">

        <div class="breadCrumbs">
            <p>@FolderLink(T("Media Folders").ToString(), "") 
                @foreach (var navigation in MediaHelpers.GetFolderNavigationHierarchy(Model.MediaPath)) {
                    <text>&#62;</text> @FolderLink(navigation.FolderName, navigation.FolderPath) 
                }
            </p>
			<fieldset>
				<input id="__requesttoken" type="hidden" value="@Html.AntiForgeryTokenValueOrchard()" />
				<input class="text-box" id="folderName" type="text" />
				<input class="button disabled" type="button" id="createFolder" value="@T("Create Folder")" />
			</fieldset>
        </div>
        <fieldset>
        <div id="file-list">
            <table class="items" summary="@T("This is a table of the images currently available for use in your application.")">
                @foreach (var mediaFolder in Model.MediaFolders) {
                    <tr>
                        <td class="media-folder" colspan="2">
                            <img src="@Href("~/Modules/Orchard.Media/Content/Admin/images/folder.gif")" height="16" width="16" class="mediaTypeIcon" alt="@T("Folder")" />
                            @FolderLink(mediaFolder.Name, mediaFolder.MediaPath)
                        </td>
                    </tr>
                }
                @if (Model.MediaFiles != null) {
                    foreach (var mediaFile in Model.MediaFiles) {
                        var src = (((IMediaService)ViewData["Service"]).GetPublicUrl(Path.Combine(Model.MediaPath, mediaFile.Name)));
                    <tr data-imgsrc="@src" class="media-item">
                        <td class="media-thumbnail">
                            <img data-filename="@src.Substring(src.LastIndexOf("/") + 1)" alt="" src="@src" onload="jQuery.mediaPicker.scalePreview(this)" />
                        </td>
                        <td class="media-details">
                            <ul class="media-summary">
                                <li><a class="media-filename" href="@src" target="_blank">@mediaFile.Name</a></li>
                                <li>@T("Added on"): @mediaFile.LastUpdated</li>
                                <li>@T("Size"): @mediaFile.Size.ToFriendlySizeString()</li>
                            </ul>
                        </td>
                    </tr>
                    }
                }
            </table>
            </div>
            @if (!String.IsNullOrWhiteSpace(Model.MediaPath)) {
                using (Html.BeginFormAntiForgeryPost(uploadAction, FormMethod.Post, new { id="lib-uploadform", enctype = "multipart/form-data", onsubmit = "jQuery.mediaPicker.uploadMedia(this)" })) { 
                <input type="hidden" name="MediaPath" value="@Model.MediaPath" />
                <label for="fileUpload">@T("Upload an image from your computer")</label>
                <input type="file" name="fileUpload" id="fileUpload"  />
                <input class="button" type="submit" id="upload" value="Upload" />
                }
            }
            <img id="img-indicator" src="@Url.Content("~/modules/orchard.mediapicker/Styles/images/synchronizing.gif")" alt="" class="throbber" />

        </fieldset>

        </div>
        <div id="file-details">
            <img alt="" id="lib-loader" style="display:none" src="" />
            <fieldset>
            <ol>
                <li>
                <label for="lib-src">@T("URL")</label>
                <input class="text-box" type="text" id="lib-src" />
                </li>

                <li>
                <label for="lib-alt">@T("Alternative Text")</label>
                <input class="text-box" type="text" id="lib-alt" />
                </li>

                <li>
                <label for="lib-class">@T("Class")</label>
                <input class="text-box" type="text" id="lib-class" />
                </li>

                <li>
                <label for="lib-style">@T("Style")</label>
                <input class="text-box" type="text" id="lib-style" />
                </li>

                <li>
                <label for="lib-align">@T("Alignment")</label>
                <select id="lib-align">
                    <option value="">None</option>
                    <option value="left">Left</option>
                    <option value="right">Right</option>
                    <option value="top">Top</option>
                    <option value="texttop">Text Top</option>
                    <option value="middle">Middle</option>
                    <option value="absmiddle">AbsMiddle</option>
                    <option value="bottom">Bottom</option>
                    <option value="absbottom">AbsBottom</option>
                    <option value="baseline">Baseline</option>
                </select>
                </li>

                <li class="group">
                <div class="image-width">
                    <label for="lib-width">@T("Width")</label>
                    <input class="text-box" type="text" id="lib-width" />&nbsp;x
                </div>
                <div class="image-height">
                    <label for="lib-height">@T("Height")</label>
                    <input class="text-box" type="text" id="lib-height" />
                </div>
                </li>

                <li>
                <input type="checkbox" id="lib-lock" checked="checked" />
                <label class="forcheckbox" for="lib-lock">@T("Lock Aspect Ratio")</label>
                </li>

                <li class="actions">
                <input type="button" id="lib-insert" class="button disabled" value="@T("Insert")" data-edittext="@T("Update")" />
                <input type="button" id="lib-cancel" class="button" value="@T("Cancel")" />
                </li>
                </ol>
            </fieldset>
        </div>

Source/src/Orchard.Web/Modules/Orchard.MediaPicker/Views/Admin/Tab_Url.cshtml
@model Orchard.Media.ViewModels.MediaFolderEditViewModel
@using Orchard.Media.Extensions;
@using Orchard.Media.Helpers;
@using Orchard.Media.Services;
@using Orchard.Media.Models;
@using Orchard.UI.Resources;
@{
    var uploadAction = Url.Action("AddFromClient", "Admin", new { area = "Orchard.Media" });
    // media directory to save uploaded files into
    var mediaPath = Request["uploadpath"];
}
        <div id="image-preview">
            <img alt="" id="img-loader" style="display:none" src="" />
            <div class="media-largepreview">
                <img alt="@T("Preview of Image")" id="img-preview" src="@Url.Content("~/modules/orchard.mediapicker/Styles/images/imagepreview.png")" onload="jQuery.mediaPicker.scalePreview(this)" />
            </div>
            <div>
                <label for="img-src">@T("URL for the image resource")</label>
                <input class="text-box" type="text" id="img-src" />
            </div>
            <div>
                @using(Html.BeginFormAntiForgeryPost(uploadAction, FormMethod.Post, new { id = "img-uploadform", enctype = "multipart/form-data", onsubmit="jQuery.mediaPicker.uploadMedia(this)"})) { 
                    <input type="hidden" name="MediaPath" value="@mediaPath" />
                    <label for="fileUpload">@T("Upload an image from your computer")</label>
                    <input type="file" name="fileUpload" id="fileUpload"  />
                    <input class="button" type="submit" id="upload" value="Upload" />
                }
				<img id="img-indicator" src="@Url.Content("~/modules/orchard.mediapicker/Styles/images/synchronizing.gif")" alt="" class="throbber" />
            </div>

        </div>
        <div id="file-details">
            <fieldset>
            <ol>
                <li>
                <label for="img-alt">@T("Alternative Text")</label>
                <input class="text-box" type="text" id="img-alt" />
                </li>

                <li>
                <label for="img-class">@T("Class")</label>
                <input class="text-box" type="text" id="img-class" />
                </li>

                <li>
                <label for="img-style">@T("Style")</label>
                <input class="text-box" type="text" id="img-style" />
                </li>

                <li>
                <label for="img-align">@T("Alignment")</label>
                <select id="img-align">
                    <option value="">None</option>
                    <option value="left">Left</option>
                    <option value="right">Right</option>
                    <option value="top">Top</option>
                    <option value="texttop">Text Top</option>
                    <option value="middle">Middle</option>
                    <option value="absmiddle">AbsMiddle</option>
                    <option value="bottom">Bottom</option>
                    <option value="absbottom">AbsBottom</option>
                    <option value="baseline">Baseline</option>
                </select>
                </li>

                <li class="group">
                <div class="image-width">
                    <label for="img-width">@T("Width")</label>
                    <input class="text-box" type="text" id="img-width" />&nbsp;x
                </div>
                <div class="image-height">
                    <label for="img-height">@T("Height")</label>
                    <input class="text-box" type="text" id="img-height" />
                </div>
                </li>

                <li>
                <input type="checkbox" id="img-lock" checked="checked" />
                <label class="forcheckbox" for="img-lock">@T("Lock Aspect Ratio")</label>
                </li>

                <li class="actions">
                <input type="button" id="img-insert" class="button disabled" value="@T("Insert")" data-edittext="@T("Update")" />
                <input type="button" id="img-cancel" class="button" value="@T("Cancel")" />
                </li>
                </ol>
            </fieldset>
        </div>

Source/src/Orchard.Web/Modules/Orchard.MediaPicker/Views/EditorTemplates/Fields/MediaGallery.Edit.cshtml
@model Orchard.MediaPicker.ViewModels.MediaGalleryFieldViewModel
@using Orchard.Environment.Configuration
@using Orchard.MediaPicker.Settings;

@{
    Style.Include("media-gallery-admin");
    Script.Require("jQueryUI_Sortable").AtFoot();
    
    var settings = Model.Field.PartFieldDefinition.Settings.GetModel<MediaGalleryFieldSettings>();
    var descriminator = Html.FieldIdFor(m => m.Field.Items);
    var safeDescriminator = descriminator.Replace("-", "_");
        
    var baseUrl = Url.Content("~/") + WorkContext.Resolve<ShellSettings>().RequestUrlPrefix;
}

<fieldset>
    <label @if(settings.Required) { <text>class="required"</text> }>@Model.Field.DisplayName</label>
    @if (HasText(settings.Hint)) {
    <span class="hint">@settings.Hint</span>
    }

    <div id="save-message-@descriminator" class="message message-Warning media-gallery-message">@T("You need to save your changes.")</div>
    <table id="media-gallery-@descriminator" class="items media-gallery" summary="@Model.Field.DisplayName">
        <colgroup>
            <col id="Col1" style="width:20px" />
            <col id="Col2" />
            <col id="Col3" />
        </colgroup>
        <thead>
            <tr>
                <th scope="col" >&nbsp;&darr;</th>
                <th scope="col">@T("Media")</th>
                <th scope="col">&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var media in Model.Items) {
                <tr>
                    <td>&nbsp;</td>
                    <td>
                        <span data-url="@media.Url" data-alt="@media.AlternateText" data-class="@media.Class" data-style="@media.Style" data-align="@media.Alignment" data-width="@media.Width" data-height="@media.Height" data-fieldid="@descriminator" class="media-gallery-item"><a title="@T("Edit")" class="media-gallery-edit" href="#">@media.Url</a></span>
                    </td>
                    <td>
                        <span data-url="@media.Url" class="media-gallery-remove button grey">@T("Remove")</span>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <span id="btn-@descriminator" class="button">@T("Add")</span>
    
    @Html.HiddenFor(m => m.SelectedItems)
</fieldset>

@using (Script.Foot()) {
<script type="text/javascript">
//<![CDATA[

    (function($) {

        var required = @(settings.Required ? "true" : "false");
        var multiple = @(settings.Multiple ? "true" : "false");
        var addButton = $('#btn-@descriminator');
        var @(safeDescriminator)_Template = '<tr><td>&nbsp;</td><td><span data-url="{url}" data-alt="{alt}" data-class="{class}" data-style="{style}" data-align="{align}" data-width="{width}" data-height="{height}" data-fieldid="@descriminator" class="media-gallery-item"><a title="@T("Edit")" class="media-gallery-edit" href="#">{url}</a></span></td><td><span class="media-gallery-remove button grey">@T("Remove")</span></td></tr>';
        
        var refreshIds = function() {
            var id = $('#@Html.FieldIdFor(m => m.SelectedItems)');
            var selectedItems = [];
            $("span[data-fieldid = @descriminator]").each(function() {
                selectedItems.push(extractModel(this));
            });

            id.val(JSON.stringify(selectedItems));
            
            // can new items be added ?
            if(!multiple && selectedItems.length > 0) {
                addButton.hide();    
            }
            else {
                addButton.show();
            }
        };

        refreshIds();
        
        // adding a new item
        addButton.click(function() {
            addButton.trigger("orchard-admin-pickimage-open", {
                callback: function(data) {
                    
                    var template = @(safeDescriminator)_Template
                        .replace( /\{url\}/g , formatUrl(data.img.src))
                        .replace( /\{alt\}/g , data.img.alt)
                        .replace( /\{class\}/g , data.img['class'])
                        .replace( /\{style\}/g , data.img.style)
                        .replace( /\{align\}/g , data.img.align)
                        .replace( /\{width\}/g , data.img.width || '0')
                        .replace( /\{height\}/g , data.img.height || '0');
                    
                    var content = $(template);
                    $('#media-gallery-@descriminator tbody').append(content);

                    refreshIds();
                    $('#save-message-@descriminator').show();
                },
                baseUrl: '@baseUrl'
            });
        });

        // editing an item
        $(".items.media-gallery").on("click", ".media-gallery-edit", function() {
            var img = extractModel($(this).parent());
            if (img.Url && img.Url.length > 2 && img.Url.substr(0, 2) == "~/") {
                img.Url = '@baseUrl' + img.Url.substr(2);
            }

            var tr = $(this).closest('tr');
            
            $(this).trigger("orchard-admin-pickimage-open", {
                img: {
                    src: img.Url,
                    alt: img.AlternateText,
                    'class': img.Class,
                    style: img.Style,
                    align: img.Alignment,
                    width: img.Width,
                    height: img.Height
                },
                baseUrl: '@baseUrl',
                //uploadMediaPath: 'images',
                callback: function (data) {
                    
                    var template = @(safeDescriminator)_Template
                         .replace( /\{url\}/g , formatUrl(data.img.src))
                         .replace( /\{alt\}/g , data.img.alt)
                         .replace( /\{class\}/g , data.img['class'])
                         .replace( /\{style\}/g , data.img.style)
                         .replace( /\{align\}/g , data.img.align)
                         .replace( /\{width\}/g , data.img.width || '0')
                         .replace( /\{height\}/g , data.img.height || '0');
                    
                    var content = $(template);
                    tr.after(content);
                    tr.remove();

                    refreshIds();
                    $('#save-message-@descriminator').show();
                }
            });
        });
        
        $('#media-gallery-@descriminator').on("click", ".media-gallery-remove", function() {
            $(this).closest('tr').remove();
            refreshIds();
            $('#save-message-@descriminator').show();
        });
            
        $("#media-gallery-@descriminator tbody").sortable({
            handle: 'td:first',
            stop: function(event, ui) {
                refreshIds();
                $('#save-message-@descriminator').show();
            }
        }).disableSelection();
        
        function formatUrl(url) {
            var applicationPath = '@HttpUtility.JavaScriptStringEncode(Url.RequestContext.HttpContext.Request.ApplicationPath.ToLower())';
        
            if (!/\/$/.test(applicationPath)) {
                applicationPath += '/';
            }
        
            if (url.substr(0, 4) != "http") {
                return '~/' + url.substr(applicationPath.length);
            }

            return url;
        }
        
        function extractModel(dom) {
            dom = $(dom);

            return {
                Url: dom.data('url'),
                AlternateText: dom.data('alt'),
                Class: dom.data('class'),
                Style: dom.data('style'),
                Alignment: dom.data('align'),
                Height: dom.data('height'),
                Width: dom.data('width')
            };
        }
        

    })(jQuery);
//]]>
</script>
}

Source/src/Orchard.Web/Modules/Orchard.MediaPicker/Views/EditorTemplates/Fields/MediaPicker.Edit.cshtml
@model Orchard.MediaPicker.Fields.MediaPickerField
@using Orchard.MediaPicker.Settings

@{
    Script.Require("jQuery").AtFoot();
    var settings = Model.PartFieldDefinition.Settings.GetModel<MediaPickerFieldSettings>();
}

<fieldset>
    <label for="@Html.FieldIdFor(m => m.Url)" @if(settings.Required) { <text>class="required"</text> }>@Model.DisplayName</label>
    @Html.TextBoxFor(m => m.Url, new { @class = "textMedium", @readonly = "readonly" }) <span id="btn-@Html.FieldIdFor(m => m.Url)" class="button">@T("Browse")</span>
    
    @if(!settings.Required) {
        <span id="clear-@Html.FieldIdFor(m => m.Url)" class="button">@T("Clear")</span>    
    }
    
    @if (HasText(settings.Hint)) {
    <span class="hint">@settings.Hint</span>
    }
    @Html.HiddenFor(m => m.AlternateText)
    @Html.HiddenFor(m => m.Class)
    @Html.HiddenFor(m => m.Style)
    @Html.HiddenFor(m => m.Alignment)
    @Html.HiddenFor(m => m.Width)
    @Html.HiddenFor(m => m.Height)

</fieldset>

@using (Script.Foot()) {

<script type="text/javascript">
//<![CDATA[

    jQuery('#clear-@Html.FieldIdFor(m => m.Url)').click(function () {
        jQuery('#@Html.FieldIdFor(m => m.Url)').val('');
    });

    jQuery('#btn-@Html.FieldIdFor(m => m.Url)').click(function () {
        
        var currentImageUrl  = $('#@Html.FieldIdFor(m => m.Url)').val();
        if (currentImageUrl && currentImageUrl.length > 2 && currentImageUrl.substr(0, 2) == "~/") {
            currentImageUrl = '@Url.Content("~/")' + currentImageUrl.substr(2);
        }
        
        jQuery('#btn-@Html.FieldIdFor(m => m.Url)').trigger("orchard-admin-pickimage-open", {
            img: {
                src: currentImageUrl,
                "class": $('#@Html.FieldIdFor(m => m.Class)').val(),
                style: $('#@Html.FieldIdFor(m => m.Style)').val(),
                alt: $('#@Html.FieldIdFor(m => m.AlternateText)').val(),
                width: $('#@Html.FieldIdFor(m => m.Width)').val(),
                height: $('#@Html.FieldIdFor(m => m.Height)').val(),
                align: $('#@Html.FieldIdFor(m => m.Alignment)').val()
            },
            uploadMediaPath: 'images',
            callback: function (data) {
                var applicationPath = '@Url.RequestContext.HttpContext.Request.ApplicationPath.ToLower()';
                if (!/\/$/.test(applicationPath)) {
                    applicationPath += '/';
                }

                var url = data.img.src;

                if (url.substr(0, 4) != "http") {
                    url = '~/' + url.substr(applicationPath.length);
                }

                jQuery('#@Html.FieldIdFor(m => m.Url)').val(url);

                var alternateText = data.img.alt;
                jQuery('#@Html.FieldIdFor(m => m.AlternateText)').val(alternateText);

                var _class = data.img['class'];
                jQuery('#@Html.FieldIdFor(m => m.Class)').val(_class);

                var style = data.img.style;
                jQuery('#@Html.FieldIdFor(m => m.Style)').val(style);

                var align = data.img.align;
                jQuery('#@Html.FieldIdFor(m => m.Alignment)').val(align);

                var width = data.img.width || "0";
                jQuery('#@Html.FieldIdFor(m => m.Width)').val(width);

                var height = data.img.height || "0";
                jQuery('#@Html.FieldIdFor(m => m.Height)').val(height);
            }
        });
    });
//]]>
</script>
}